In [113]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

import preprocessor as pp

In [48]:
path = 'cleaned_dataset/'

In [50]:
df = pp.read_clean_file(path)
df

,type,start_time,ambient_temperature,battery_id,test_id,uid,filename,Capacity,Re,Rct
0,discharge,2010-07-21 15:00:35.093000,4,B0047,0,1,00001.csv,1.6743047446975208,NaN,NaN
1,impedance,2010-07-21 16:53:45.968000,24,B0047,1,2,00002.csv,NaN,0.05605783343888099,0.20097016584458333
2,charge,2010-07-21 17:25:40.670999,4,B0047,2,3,00003.csv,NaN,NaN,NaN
3,impedance,2010-07-21 20:31:05.000000,24,B0047,3,4,00004.csv,NaN,0.05319185850921101,0.16473399914864734
4,discharge,2010-07-21 21:02:56.984000,4,B0047,4,5,00005.csv,1.5243662105099023,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7560,impedance,2010-09-30 07:36:45.045999,24,B0055,247,7561,07561.csv,NaN,0.0968087979207628,0.15489738203707232
7561,discharge,2010-09-30 08:08:36.328000,4,B0055,248,7562,07562.csv,1.0201379996149256,NaN,NaN
7562,charge,2010-09-30 08:48:54.250000,4,B0055,249,7563,07563.csv,NaN,NaN,NaN
7563,discharge,2010-09-30 11:50:17.687000,4,B0055,250,7564,07564.csv,0.9907591663373165,NaN,NaN
7564,charge,2010-09-30 12:31:10.170999,4,B0055,251,7565,07565.csv,NaN,NaN,NaN

In [54]:
df_discharges = pp.get_discharges(path, df)
df_discharges

,start_time,ambient_temperature,battery_id,uid,filename,Capacity,cycle_number,mean_voltage,max_voltage,min_voltage,mean_current,max_current,mean_temperature,max_temperature,discharge_time
0,2010-07-21 15:00:35.093000,4,B0047,1,00001.csv,1.6743047446975208,1,3.475266,4.246764,2.470612,-0.952767,0.000252,8.272423,12.376816,6436.141
4,2010-07-21 21:02:56.984000,4,B0047,5,00005.csv,1.5243662105099023,2,3.476559,4.186636,2.477662,-0.983889,-0.001536,8.210715,11.314903,5650.265
6,2010-07-22 01:40:06.217999,4,B0047,7,00007.csv,1.5080762969973425,3,3.470767,4.199923,2.470710,-0.983889,-0.000746,7.954455,11.624528,5590.907
8,2010-07-22 06:16:21.780999,4,B0047,9,00009.csv,1.4835577960067696,4,3.467551,4.199569,2.465458,-0.978947,0.000303,7.985865,11.092924,5543.610
10,2010-07-22 10:51:48.203000,4,B0047,11,00011.csv,1.4671391666146525,5,3.462839,4.199397,2.465765,-0.976262,0.000422,8.009427,11.020979,5499.046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7553,2010-09-29 19:50:59.780999,4,B0055,7554,07554.csv,1.0285269676595319,98,3.370549,4.206432,2.495933,-1.676154,0.001937,10.889278,15.515116,2345.000
7555,2010-09-29 23:33:00.890000,4,B0055,7556,07556.csv,0.9816844358987022,99,3.358032,4.203481,2.493974,-1.656642,0.001502,11.125862,17.410883,2363.047
7557,2010-09-30 03:15:20.437000,4,B0055,7558,07558.csv,1.0127121434171131,100,3.330593,4.203063,2.494585,-1.736640,0.002544,11.180258,17.541633,2316.687
7561,2010-09-30 08:08:36.328000,4,B0055,7562,07562.csv,1.0201379996149256,101,3.345081,4.197674,2.497096,-1.713216,0.003379,11.102810,16.684126,2322.000
7563,2010-09-30 11:50:17.687000,4,B0055,7564,07564.csv,0.9907591663373165,102,3.341122,4.202804,2.496842,-1.685356,0.001585,11.412928,18.127312,2357.687

In [89]:
BATTERIES = sorted(df['battery_id'].value_counts().index.tolist())
print(len(BATTERIES))
bat_tr, bat_te = train_test_split(BATTERIES, test_size=0.28, random_state=42)
print(bat_tr)
print(bat_te)
df_tr = df[df['battery_id'].isin(bat_tr)]
df_te = df[df['battery_id'].isin(bat_te)]

34
['B0005', 'B0025', 'B0039', 'B0040', 'B0026', 'B0034', 'B0032', 'B0006', 'B0007', 'B0053', 'B0018', 'B0052', 'B0046', 'B0054', 'B0045', 'B0041', 'B0048', 'B0027', 'B0043', 'B0056', 'B0028', 'B0031', 'B0036', 'B0051']
['B0038', 'B0042', 'B0050', 'B0049', 'B0029', 'B0047', 'B0044', 'B0033', 'B0055', 'B0030']

In [91]:
bat_tr, bat_val = train_test_split(BATTERIES,test_size=0.2,random_state=21)
print(bat_tr)
print(bat_val)

df_tr = df[df['battery_id'].isin(bat_tr)]
df_val = df[df['battery_id'].isin(bat_val)]
dis_tr = pp.get_discharges(path, df_tr)
dis_val = pp.get_discharges(path, df_val)

['B0055', 'B0026', 'B0042', 'B0045', 'B0028', 'B0050', 'B0032', 'B0041', 'B0027', 'B0053', 'B0044', 'B0051', 'B0056', 'B0033', 'B0036', 'B0029', 'B0031', 'B0040', 'B0007', 'B0018', 'B0054', 'B0052', 'B0039', 'B0025', 'B0047', 'B0038', 'B0030']
['B0006', 'B0043', 'B0049', 'B0005', 'B0034', 'B0048', 'B0046']

In [111]:
dis_tr

,start_time,ambient_temperature,battery_id,uid,filename,Capacity,cycle_number,mean_voltage,max_voltage,min_voltage,mean_current,max_current,mean_temperature,max_temperature,discharge_time
0,2010-07-21 15:00:35.093000,4,B0047,1,00001.csv,1.6743047446975208,1,3.475266,4.246764,2.470612,-0.952767,0.000252,8.272423,12.376816,6436.141
4,2010-07-21 21:02:56.984000,4,B0047,5,00005.csv,1.5243662105099023,2,3.476559,4.186636,2.477662,-0.983889,-0.001536,8.210715,11.314903,5650.265
6,2010-07-22 01:40:06.217999,4,B0047,7,00007.csv,1.5080762969973425,3,3.470767,4.199923,2.470710,-0.983889,-0.000746,7.954455,11.624528,5590.907
8,2010-07-22 06:16:21.780999,4,B0047,9,00009.csv,1.4835577960067696,4,3.467551,4.199569,2.465458,-0.978947,0.000303,7.985865,11.092924,5543.610
10,2010-07-22 10:51:48.203000,4,B0047,11,00011.csv,1.4671391666146525,5,3.462839,4.199397,2.465765,-0.976262,0.000422,8.009427,11.020979,5499.046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7553,2010-09-29 19:50:59.780999,4,B0055,7554,07554.csv,1.0285269676595319,98,3.370549,4.206432,2.495933,-1.676154,0.001937,10.889278,15.515116,2345.000
7555,2010-09-29 23:33:00.890000,4,B0055,7556,07556.csv,0.9816844358987022,99,3.358032,4.203481,2.493974,-1.656642,0.001502,11.125862,17.410883,2363.047
7557,2010-09-30 03:15:20.437000,4,B0055,7558,07558.csv,1.0127121434171131,100,3.330593,4.203063,2.494585,-1.736640,0.002544,11.180258,17.541633,2316.687
7561,2010-09-30 08:08:36.328000,4,B0055,7562,07562.csv,1.0201379996149256,101,3.345081,4.197674,2.497096,-1.713216,0.003379,11.102810,16.684126,2322.000
7563,2010-09-30 11:50:17.687000,4,B0055,7564,07564.csv,0.9907591663373165,102,3.341122,4.202804,2.496842,-1.685356,0.001585,11.412928,18.127312,2357.687

In [109]:
features = ['ambient_temperature', 
            'cycle_number',
            'mean_voltage',
            'max_voltage',
            'min_voltage',
            'mean_current',
            'max_current',
            'mean_temperature',
            'max_temperature',
            'discharge_time']
disx_tr = dis_tr[features].values
disy_tr = dis_tr['Capacity'].values
disx_val = dis_val[features].values
disy_val = dis_val['Capacity'].values

In [131]:
for i in df_tr.iloc[0]:
    print(i, type(i))

disy_tr[0]

discharge <class 'str'>
2010-07-21 15:00:35.093000 <class 'pandas._libs.tslibs.timestamps.Timestamp'>
4 <class 'numpy.int64'>
B0047 <class 'str'>
0 <class 'numpy.int64'>
1 <class 'numpy.int64'>
00001.csv <class 'str'>
1.6743047446975208 <class 'str'>
nan <class 'float'>
nan <class 'float'>

'1.6743047446975208'

In [117]:
rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=12,
    random_state=21
)
rf.fit(disx_tr, disy_tr)

pred_rf = rf.predict(disx_val)

print("RF MAE:", mean_absolute_error(disy_val, pred_rf))
print("RF MSE:", np.sqrt(mean_squared_error(disy_val, pred_rf)))
print("RF R2:", r2_score(disy_val, pred_rf))

ValueError: could not convert string to float: '[]'